/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as destChainSol from "./Dest_Chain.sol";
export type { destChainSol };
import type * as sourceChainSol from "./Source_Chain.sol";
export type { sourceChainSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Stake } from "./Stake";
