/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAlgebraSwapCallback } from "./IAlgebraSwapCallback";
export type { IStake } from "./IStake";
export type { ISwapRouter } from "./ISwapRouter";
export type { IWMATIC } from "./IWMATIC";
