/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWMATIC,
  IWMATICInterface,
} from "../../../contracts/interfaces/IWMATIC";

const _abi = [
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWMATIC__factory {
  static readonly abi = _abi;
  static createInterface(): IWMATICInterface {
    return new utils.Interface(_abi) as IWMATICInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWMATIC {
    return new Contract(address, _abi, signerOrProvider) as IWMATIC;
  }
}
