/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IStake,
  IStakeInterface,
} from "../../../artifacts/contracts/IStake";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "onBehalfOf",
        type: "address",
      },
    ],
    name: "stake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "unstake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IStake__factory {
  static readonly abi = _abi;
  static createInterface(): IStakeInterface {
    return new utils.Interface(_abi) as IStakeInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IStake {
    return new Contract(address, _abi, signerOrProvider) as IStake;
  }
}
